openapi: 3.0.0
info:
  title: Pick up store
  description: Pick up store - E-commerce
  version: 0.1.9

paths:
  /:
    get:
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: string
