openapi: 3.0.0
info:
  title: Pick up store
  description: Pick up store - E-commerce
  version: 0.1.9

paths:
  /main:
    get:
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: string

  /updateCart/{product_id}:
    put:
      summary: Update the amount of a product in the cart
      parameters:
        - in: path
          name: product_id
          required: true
          description: The ID of the product to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_amount:
                  type: integer
                  description: The new amount of the product in the cart
      responses:
        "200":
          description: The product was successfully updated in the cart

  /deleteProduct/{product_id}:
    delete:
      summary: Delete product from cart
      parameters:
        - in: path
          name: product_id
          required: true
          description: The ID of the product to delete
          schema:
            type: string
      responses:
        "200":
          description: The product was successfully deleted from the cart.
